services:
  rassilka:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./rassilka:/rassilka
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"

    
    env_file:
      - ./.env.dev
    depends_on:
      - db
             
  db:
    image: postgres:12-alpine
    env_file:
      - ./.env.dev
    volumes: 
      - pgdata:/var/lib/postgresql/data	

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A rassilka beat -l info
    
    volumes:
      - ./rassilka:/rassilka
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - rassilka

volumes:
  pgdata: