# Generated by Django 4.2.3 on 2023-07-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='msg',
            options={'ordering': ['msgId']},
        ),
    ]
