# Generated by Django 4.2.3 on 2023-07-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='api_key',
            field=models.TextField(blank=True),
        ),
    ]
